core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('rating.urls')),
]

rating/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'
urlpatterns = [
    path('', home, name='home'),
    path('rate-image/', rate_img, name="rate")
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rating/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class RateStar(models.Model):
    img = models.ImageField(upload_to="image/")
    score = models.IntegerField(default=0,
            validators=[
                MaxValueValidator(5),
                MinValueValidator(0),
            ]
    )

    def __str__(self):
        return f"{str(self.pk)}-chi"

rating/views.py
from django.shortcuts import render
from .models import *
from django.http import JsonResponse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Avg

# def home(request):
#     rate = RateStar.objects.filter(score=2).order_by("?").first()
#     context = {
#         "rate": rate
#     }
#     return render(request, "home.html", context )

# def rate_img(request):
#     if request.method == "POST":
#         el_id = request.POST.get("el_id")
#         val = request.POST.get("val")
#         rate = RateStar.objects.get(id=el_id)
#         rate.score = val
#         rate.save()
#         return JsonResponse({"success": "true", "score": val}, safe=False)
#     return JsonResponse({"success": "false"})
def home(request):
    rate = RateStar.objects.filter(score=2).order_by("?").first()
    avg_rate = RateStar.objects.aggregate(Avg("score"))
    context = {
        "rate": rate,
        "avg_rate": avg_rate
    }
    return render(request, "home.html", context )

def rate_img(request):
    if request.method == "POST":
        el_id = request.POST.get("el_id")
        val = request.POST.get("val")
        rate = RateStar.objects.get(id=el_id)
        rate.score = val
        rate.save()
        return JsonResponse({"success": "true", "score": val}, safe=False)
    return JsonResponse({"success": "false"})

rating/templates/home.html
<!DOCTYPE html>{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <title>Document</title>
</head>

<body>
    <style>
        body {
            display: grid;
            justify-content: center;
            align-items: center;
            margin-left: auto;
            margin-right: auto;
            min-height: 100vh;
        }
        .checked {
            color: rgb(217, 255, 0);
        }
        form {
            position: relative;
            bottom: 250px;
        }
        .fa-3x {
            position: relative;
            right: 12px;
            border: none;
            background: none;
            margin-top: 30px;
        }
        .btns {
            background-color: inherit !important;
            border: 0 !important;
        }

        .btn-11 {
            position: relative;
            bottom: 40px;
            border: none;
            border-radius: 50px;
            background: rgb(47, 33, 251);
            background: linear-gradient(0deg, rgb(33, 73, 251) 0%, rgb(76, 113, 234) 100%);
            color: #fff;
            overflow: hidden;
            width: 120px;
            height: 35 px;
            font-size: 27px;
        }

        .btn-11:hover {
            text-decoration: none;
            color: #fff;
        }

        .btn-11:before {
            position: absolute;
            content: '';
            display: inline-block;
            top: -180px;
            left: 0;
            width: 30px;
            height: 100%;
            background-color: #fff;
            animation: shiny-btn1 3s ease-in-out infinite;
        }

        .btn-11:hover {
            opacity: .7;
        }

        .btn-11:active {
            box-shadow: 4px 4px 6px 0 rgba(255, 255, 255, .3),
                -4px -4px 6px 0 rgba(116, 125, 136, .2),
                inset -4px -4px 6px 0 rgba(255, 255, 255, .2),
                inset 4px 4px 6px 0 rgba(0, 0, 0, .2);
        }


        @keyframes shiny-btn1 {
            0% {
                -webkit-transform: scale(0) rotate(45deg);
                opacity: 0;
            }

            80% {
                -webkit-transform: scale(0) rotate(45deg);
                opacity: 0.5;
            }

            81% {
                -webkit-transform: scale(4) rotate(45deg);
                opacity: 1;
            }

            100% {
                -webkit-transform: scale(50) rotate(45deg);
                opacity: 0;
            }
        }
        .h3 {
            position: relative;
            top: 300px;
        }
        .h1 {
            position: relative;
            bottom: 100px;
        }
        .box {
            display: flex;
            position: relative;
            bottom: 270px;
        }
    </style>
    {% if rate %}
    <img src="{{ rate.img.url }}" alt="" width="500" height="400">
    <div class="frame">

        <a href="{% url 'blog:home' %}"><button class="custom-btn btn-11">Next<div class="dot"></div></button></a>

        <p style="font-family: Andale Mono, monospace;">

        <form method="post" class="rate-form" id="{{ rate.id }}">
            {% csrf_token %}
            <button type="submit" class="fa fa-star fa-3x btns " id="first"></button>
            <button type="submit" class="fa fa-star fa-3x btns " id="second"></button>
            <button type="submit" class="fa fa-star fa-3x btns " id="third"></button>
            <button type="submit" class="fa fa-star fa-3x btns" id="fourth"></button>
            <button type="submit" class="fa fa-star fa-3x btns" id="fifth"></button>
            <h3 class="h3">{{ avg_rate.score__avg }}</h3>
            <br>
            <div id="confirm-box"></div>
        </form>
        <script src="{% static 'main.js' %}"></script>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        {% else %}
        <h3 class="h3">{{ avg_rate.score__avg }}</h3>
        <h1 class="h1">Rate qilgani rasm qolmadi!</h1>
        <div class="box">
            <button type="submit" class="fa fa-star fa-3x btns one " id="first"></button>
            <button type="submit" class="fa fa-star fa-3x btns two " id="second"></button>
            <button type="submit" class="fa fa-star fa-3x btns three " id="third"></button>
            <button type="submit" class="fa fa-star fa-3x btns four" id="fourth"></button>
            <button type="submit" class="fa fa-star fa-3x btns five" id="fifth"></button>
        </div>
        {% endif %}
</body>

</html>